# Generated by Django 5.0.7 on 2024-08-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desc',
            new_name='description',
        ),
    ]
